In [3]:
# 14.1.1 为什么要进行报表自动化
# （1）提高工作效率
# （2）减少错误

In [2]:
# 14.1.2 什么样的报表适合自动化
# 使用频率
# 开发时间
# 需求变更频率
# 流程是否标准

In [4]:
# 14.1.3 如何实现报表自动化
# 表格包括销售额、客流量、客单价三个指标的本月累计、上月同期、去年同期、环比、同比这几个数值

In [17]:
# 导入源数据
import pandas as pd
import numpy as np
from datetime import datetime
data=pd.read_excel("/Users/caiqing/Documents/我的PYTHON/张俊红《对比Excel,轻松学习Python数据分析》/对比Excel,轻松学习Python数据分析数据集/order.xlsx",parse_dates=['成交时间'])
data

,商品ID,类别ID,门店编号,单价,销量,成交时间,订单ID
0,30006206,915000003,CDNL,25.23,0.328,2018-01-01,20170103CDLG000210052759
1,30163281,914010000,CDNL,2.00,2.000,2018-01-02,20170103CDLG000210052759
2,30200518,922000000,CDNL,19.62,0.230,2018-01-03,20170103CDLG000210052759
3,29989105,922000000,CDNL,2.80,2.044,2018-01-04,20170103CDLG000210052759
4,30179558,915000100,CDNL,47.41,0.226,2018-01-05,20170103CDLG000210052759
5,30022232,960000000,CDNL,0.30,1.000,2018-01-06,20170103CDLG000210052759
6,30179520,915000100,CDNL,77.52,0.086,2018-01-07,20170103CDLG000210052759
7,30184351,915000106,CDNL,15.57,0.420,2018-01-08,20170103CDLG000210052759
8,30184351,915000106,CDNL,15.58,0.470,2018-01-09,20170103CDLG000210052759
9,29989059,922000003,CDNL,1.98,1.212,2018-01-10,20170103CDLG000210052759
10,30214802,925090000,CDNL,27.43,1.455,2018-01-11,20170103CDLG000210052760
11,30006343,915030400,CDNL,3.98,2.294,2018-01-12,20170103CDLG000210052760
12,30214814,925090000,CDNL,33.43,1.568,2018-01-13,20170103CDLG000210052760
13,30031870,915030401,CDNL,8.17,2.138,2018-01-14,20170103CDLG000210052760
14,29989059,922000003,CDNL,1.98,1.566,2018-01-15,20170103CDLG000210052760
15,30077387,930000204,CDNL,18.52,1.000,2018-01-16,20170103CDLG000210052761
16,30008381,912060301,CDNL,19.44,0.434,2018-01-17,20170103CDLG000210052761
17,29989153,923000006,CDNL,7.60,1.165,2018-01-18,20170103CDLG000210052761
18,30008276,911010501,CDNL,15.43,0.487,2018-01-19,20170103CDLG000210052761
19,29991814,930000204,CDNL,19.52,1.000,2018-01-20,20170103CDLG000210052761
20,30022232,960000000,CDNL,0.30,1.000,2018-01-21,20170103CDLG000210052761
21,30008274,911010501,CDNL,27.21,0.877,2018-01-22,20170103CDLG000210052761
22,30026255,915030104,CDNL,3.32,2.868,2018-01-23,20170103CDLG000210052762
23,30133582,914050000,CDNL,1.50,1.000,2018-01-24,20170103CDLG000210052763
24,30133582,914050000,CDNL,1.50,1.000,2018-01-25,20170103CDLG000210052763
25,30133582,914050000,CDNL,1.50,1.000,2018-01-26,20170103CDLG000210052763
26,30023041,923000006,CDNL,3.20,1.062,2018-01-27,20170103CDLG000210052764
27,29989099,922000008,CDNL,1.58,0.570,2018-01-28,20170103CDLG000210052764
28,29989098,922000001,CDNL,2.80,0.472,2018-01-29,20170103CDLG000210052765
29,29989077,922000008,CDNL,11.59,0.543,2018-01-30,20170103CDLG000210052765
...,...,...,...,...,...,...,...
3448,30143065,911010100,CDXL,29.42,1.000,2017-02-17,20170103CDLG000510025138
3449,30010587,914070201,CDXL,4.12,1.000,2017-02-18,20170103CDLG000510025138
3450,30173850,920090000,CDXL,10.62,0.782,2017-02-19,20170103CDLG000510025138
3451,30034836,931050100,CDXL,14.52,1.000,2017-02-20,20170103CDLG000510025139
3452,29998004,931020303,CDXL,3.12,1.000,2017-02-21,20170103CDLG000510025139
3453,29998004,931020303,CDXL,3.12,1.000,2017-02-22,20170103CDLG000510025139
3454,30020269,923000101,CDXL,7.60,1.140,2017-02-23,20170103CDLG000510025139
3455,30203637,923000006,CDXL,3.20,1.927,2017-02-24,20170103CDLG000510025140
3456,30203637,923000006,CDXL,3.20,2.318,2017-02-25,20170103CDLG000510025140
3457,30174841,923000008,CDXL,6.80,0.919,2017-02-26,20170103CDLG000510025140
3458,29989048,922000001,CDXL,1.98,1.768,2017-02-27,20170103CDLG000510025140
3459,29989059,922000003,CDXL,1.98,1.970,2017-02-28,20170103CDLG000510025140
3460,29989077,922000008,CDXL,13.59,0.637,2017-02-28,20170103CDLG000510025140
3461,30026026,935010702,CDXL,2.50,2.000,2017-02-27,20170103CDLG000510025141
3462,30214814,925090000,CDXL,33.42,2.090,2017-02-01,20170103CDLG000510025143
3463,29989049,922000001,CDXL,1.98,0.556,2017-02-01,20170103CDLG000510025144
3464,30026118,915020000,CDXL,4.92,0.868,2017-02-02,20170103CDLG000510025144
3465,29989059,922000003,CDXL,1.98,1.111,2017-02-03,20170103CDLG000510025144
3466,30006040,915010000,CDXL,9.57,0.894,2017-02-04,20170103CDLG000510025144
3467,30040629,922000005,CDXL,15.62,0.225,2017-02-05,20170103CDLG000510025144
3468,30006039,915010001,CDXL,11.58,1.028,2017-02-06,20170103CDLG000510025144
3469,30005192,914010000,CDXL,9.52,1.000,2017-02-07,20170103CDLG000510025146
3470,30023041,923000006,CDXL,3.20,1.620,2017-02-08,20170103CDLG000510025146
3471,30038941,911010002,CDXL,17.62,1.000,2017-02-09,20170103CDLG000510025146
3472,30096418,912060403,CDXL,19.42,0.879,2017-02-10,20170103CDLG000510025147
3473,30031870,915030401,CDXL,6.58,0.862,2017-02-11,20170103CDLG000510025147
3474,30008276,911010501,CDXL,15.42,0.481,2017-02-12,20170103CDLG000510025148
3475,30033854,910000000,CDXL,9.62,1.000,2017-02-13,20170103CDLG000510025149
3476,30206214,910000000,CDXL,15.62,1.000,2017-02-14,20170103CDLG000510025150
3477,30129510,925090000,CDXL,23.21,0.312,2017-02-15,20170103CDLG000510025151

In [19]:
# 预览数据
data.head()

,商品ID,类别ID,门店编号,单价,销量,成交时间,订单ID
0,30006206,915000003,CDNL,25.23,0.328,2018-01-01,20170103CDLG000210052759
1,30163281,914010000,CDNL,2.00,2.000,2018-01-02,20170103CDLG000210052759
2,30200518,922000000,CDNL,19.62,0.230,2018-01-03,20170103CDLG000210052759
3,29989105,922000000,CDNL,2.80,2.044,2018-01-04,20170103CDLG000210052759
4,30179558,915000100,CDNL,47.41,0.226,2018-01-05,20170103CDLG000210052759

In [21]:
# 查看源数据类型
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3478 entries, 0 to 3477
Data columns (total 7 columns):
商品ID    3478 non-null int64
类别ID    3478 non-null int64
门店编号    3478 non-null object
单价      3478 non-null float64
销量      3478 non-null float64
成交时间    3478 non-null datetime64[ns]
订单ID    3478 non-null object
dtypes: datetime64[ns](1), float64(2), int64(2), object(2)
memory usage: 190.3+ KB

In [30]:
# parse_dates参数表示将数据解析为时间格式
# 计算本月相关指标
This_month = data[(data['成交时间']>=datetime(2018,2,1)) & (data['成交时间'] <=datetime(2018,2,28))]
# 销售额计算
sales_1=(This_month['销量']*This_month['单价']).sum()
# 客流量计算
traffic_1=This_month['订单ID'].drop_duplicates().count()
#客单价计算
s_t_1=sales_1/traffic_1
print("本月销售额为:{:.2f},客流量为:{},客单价为:{:.2f}".format(sales_1,traffic_1,s_t_1))

本月销售额为:10412.78,客流量为:343,客单价为:30.36

In [34]:
# 计算上月相关指标
last_month = data[(data['成交时间']>=datetime(2018,1,1))&(data['成交时间']<=datetime(2018,1,31))]
# 销售额计算
sales_2=(last_month['销量']*last_month['单价']).sum()
# 客流量计算
traffic_2=last_month['订单ID'].drop_duplicates().count()
# 客单价计算
s_t_2=sales_2/traffic_2
print('本月销售额为:{:.2f},客流量为:{},客单价为:{:.2f}'.format(sales_2,traffic_2,s_t_2))

本月销售额为:9940.97,客流量为:315,客单价为:31.56

In [36]:
# 计算去年同期相关指标
same_month=data[(data['成交时间']>=datetime(2017,2,1))&(data['成交时间']<=datetime(2017,2,28))]
# 销售额计算
sales_3=(same_month['销量']*same_month['单价']).sum()
# 客流量计算
traffic_3=same_month['订单ID'].drop_duplicates().count()
# 客单价计算
s_t_3=sales_3/traffic_3
print('本月销售额:{:.2f},客流量:{},客单价为:{:.2f}'.format(sales_3,traffic_3,s_t_3))

本月销售额:8596.31,客流量:262,客单价为:32.81

In [37]:
# 利用函数提高编码效率

In [58]:
import pandas as pd
import numpy as np
from datetime import datetime
data=pd.read_excel("/Users/caiqing/Documents/我的PYTHON/张俊红《对比Excel,轻松学习Python数据分析》/对比Excel,轻松学习Python数据分析数据集/order.xlsx",parse_dates=['成交时间'])

def get_month_data(data):
    sale = (data['单价']*data['销量']).sum()
    traffic = data["订单ID"].drop_duplicates().count()
    s_t = sale/traffic
    return(sale,traffic,s_t)
# 计算本月相关指标
sale_1,traffic_1,s_t_1=get_month_data(This_month)
# 计算上月相关指标
sale_2,traffic_2,s_t_2=get_month_data(last_month)
# 计算去年同期相关指标
sale_3,traffic_3,s_t_3=get_month_data(same_month)
          
report = pd.DataFrame([[sale_1,sales_2,sale_3],
                      [traffic_1,traffic_2,traffic_3],
                      [s_t_1,s_t_2,s_t_3]],
                     columns=('本月累计','上月同期','去年同期'),
                     index=('销售额','客流量','客单价'))
report

             本月累计         上月同期         去年同期
销售额  10412.780070  9940.972910  8596.313470
客流量    343.000000   315.000000   262.000000
客单价     30.357959    31.558644    32.810357

In [59]:
# 添加同比和环比字段
report['环比']=report['本月累计']/report['上月同期']-1
report['同比']=report['本月累计']/report['去年同期']-1
report

             本月累计         上月同期         去年同期        环比        同比
销售额  10412.780070  9940.972910  8596.313470  0.047461  0.211308
客流量    343.000000   315.000000   262.000000  0.088889  0.309160
客单价     30.357959    31.558644    32.810357 -0.038046 -0.074745

In [61]:
report.to_excel("/Users/caiqing/Documents/我的PYTHON/张俊红《对比Excel,轻松学习Python数据分析》/对比Excel,轻松学习Python数据分析数据集/第14章订单同比和环比.xlsx",encoding='utf-8-sig')